# Generated by Django 4.2.3 on 2023-09-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imageurl',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
