# Generated by Django 4.2.3 on 2023-09-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='imageurl',
            new_name='imagename',
        ),
    ]
