# Generated by Django 4.2.3 on 2023-09-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_imageurl_listing_imagename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startingprice',
            new_name='startingbid',
        ),
    ]
