# Generated by Django 4.2.3 on 2023-09-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_startingprice_listing_startingbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='categoryname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
