# Generated by Django 4.2.3 on 2023-09-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_watchlist_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='isactive',
        ),
    ]
