# Generated by Django 4.2.3 on 2023-09-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_bid_listing_alter_comment_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
